### ISSUE TITLE
отслеживание приглашений

### ISSUE THREAD

**Issue by JustLian** [Euphoverse/ShikimoriBot#8]
- [x] система отслеживания
- [x] награды: 5 дней спонсорки за каждое пятое приглашение и 50 * {invite_count} монет за остальные

**Comment by Filo6699** [comment]
- [x] при заходе с приглашения с последним использованием (uses 1/1), оно мгновенно удаляется и бот не может обнаружить пригласившего нового участника пользователя

**Comment by JustLian** [comment]
пользователь может со второго аккаунта выходить и заходить обратно на сервер. Нужно добавить ключ "max_invites" в БД и сделать от этого защиту используя макс. кол-во инвайтов @Filo6699
